branch-defaults:
  main:
    environment: image-filter-udagram-dev
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image_filter_udagram
  branch: null
  default_ec2_keyname: app-key-pair
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
